### ISSUE TITLE
Change Edition from 2018 to 2015

### ISSUE THREAD

**Issue by neachdainn** [jeikabu/nng-rust#10]
This crate should support as many versions of Rust as possible and I believe specifying the "edition" in the Cargo.toml locks it to 1.31 and above. To my knowledge, the Bindgen generated files and the hand-written files aren't doing anything that requires any relatively new Rust version.

We should also set up CI such that it makes sure we don't accidentally bump the minimum Rust version.

**Comment by neachdainn** [comment]
I bring this up because I will need to support Nng-rs on Ubuntu 14.04 which currently is at Rust v1.30 and may or may not ever upgrade. In this particular situation, Rustup is _not_ an option.

**Comment by jake-ruyi** [comment]
Ok with me.  2015 and 2018 libraries can supposedly be linked together without issue.
You able to take a look at getting this working?
Thought I remembered seeing a bindgen option related to editions, but maybe it was [rust_target](https://docs.rs/bindgen/0.47.3/bindgen/struct.Builder.html#method.rust_target) (which is probably still useful).

For CI I'm pretty sure we can just specify we want 1.30.

**Comment by jeikabu** [comment]
Ok with me. 2015 and 2018 libraries can supposedly be linked together without issue.
You able to take a look at getting this working?
Thought I remembered seeing a bindgen option related to editions, but maybe it was [rust_target](https://docs.rs/bindgen/0.47.3/bindgen/struct.Builder.html#method.rust_target) (which is probably still useful).

For CI I'm pretty sure we can just specify we want 1.30.

**Comment by neachdainn** [comment]
The libraries can be linked together but I do not know what a pre-1.31 Cargo will do with the "edition" key. Setting the `rust_target` would actually be a very good thing to do - I had no idea that option even existed. A good plan would probably be to use CI/Docker/Something to see the minimum version that the current setup supports, and then use that version in CI.

I'm not categorically against using newer Rust versions, I just know that there has been some discussion in the Rust community about supporting old versions ([1] [2]), and I happen to know that I'll be targeting a platform that is stuck at 1.30, so I figured the discussion would be worth having.

[1]: https://www.reddit.com/r/rust/comments/auyou5/support_for_old_compilers_in_libs_rand/
[2]: https://github.com/BurntSushi/ripgrep/issues/1019

**Comment by jeikabu** [comment]
I definitely support the idea of the lowest-level/most-common dependencies having the least-restrictive requirements possible.

**Comment by neachdainn** [comment]
I am currently working on a branch of Nng-rs that utilizes this crate as the bindings to NNG. Once that is complete, I will support publishing this to Crates.io as soon as this issue is resolved.

I am also open to waiting for the next NNG release, if we so choose.

**Comment by jeikabu** [comment]
I hadn't noticed the type of the returns because I immediately turn everything into an enum.

Sounds like this is pretty close.  Nng development has slowed down the past month so I've been focused on other things.

**Comment by neachdainn** [comment]
> I hadn't noticed the type of the returns because I immediately turn everything into an enum.

It's a very minor pain point and having a unified nng-sys far outweighs this. But for me, it appears in a few small places. E.g., 

```rust
let flags = if nonblocking { nng_sys::NNG_FLAG_NONBLOCK } else { 0 }; // u32
let rv = nng_sys::nng_listen(handle,, addr, ptr::null_mut(), flags as i32); // i32
if rv != 0 {
    Error::from_code(rv as u32) // All error constants are u32
}
else {
    // ...
}
```

> Sounds like this is pretty close.

Yeah, but I did just discover [an issue][1] when compiling with 1.31. I'm looking into it now to see what is happening.

[1]: https://gitlab.com/neachdainn/nng-rs/-/jobs/189436808

**Comment by neachdainn** [comment]
I just realized that tracking the minimum version on Nng-rs also tracks the minimum version of this library, so I am good to begin the process of moving this formally into the NNG domain and then pushing it to Crates.io as soon as #16 is resolved.

**Comment by neachdainn** [comment]
I'm closing this since I now only need to support back to 1.31 and there are tests in place to make sure that the minimum version doesn't get bumped by accident.
