### ISSUE TITLE
NNG master tracking branch

### ISSUE THREAD

**Issue by neachdainn** [jeikabu/nng-rust#19]
I encountered a [pretty bad bug][1] in NNG that is requiring me to link against the current NNG master branch. I think this means I will be maintaining an (probably infrequently updated) branch of this repository that links against the NNG master branch.

@jeikabu: Is this something you would want me to maintain here or on a private fork?

[1]: https://github.com/nanomsg/nng/issues/931

**Comment by jeikabu** [comment]
Here is fine

**Comment by neachdainn** [comment]
Sounds good. Thanks!

**Comment by jeikabu** [comment]
Forgot to mention, might want to start with the "1.2" branch, the changes are minor but then at least things don't diverge too much. Guess I could update it today....

**Comment by neachdainn** [comment]
> Guess I could update it today

No need for that on my end. One of my helper libraries is currently still using an old version of Nnn-rs so I'm maintaining a master link on old sys crate. Once I update the helper library, I'll make the master branch on here.

> might want to start with the "1.2" branch

Will do!
