### ISSUE TITLE
Documentation Oddities

### ISSUE THREAD

**Issue by neachdainn** [jeikabu/nng-rust#5]
* The documentation is being generated for `nng_*_s` instead of `nng_*`. I don't know if this is something we can really fix or if we just have to let Bindgen do its thing.

* I am not seeing the initialization constants in the documentation. Perhaps this is related to the previous oddity, since the constants are `impl <type alias> { const ... }`?

**Comment by jeikabu** [comment]
Haven't had a chance to look into this just yet.  You're looking at `cargo doc --open`, right?
I haven't gone very deep on the doc generation yet, so I'm not sure how to move things around automatically.

**Comment by neachdainn** [comment]
I'm closing this because I don't think there's much we can do about it without completely redesigning this crate (i.e., not use Bindgen). Plus, anyone using this crate is probably looking at the actual NNG docs, not the ones Cargo generates.
