### ISSUE TITLE
Strings not arrays of `c_char`

### ISSUE THREAD

**Issue by neachdainn** [jeikabu/nng-rust#7]
The strings that are defined using `#define` are implemented (on my machine) as arrays of `u8` instead of arrays of `c_char`. Do we know that this is going to be the same across all platforms?

**Comment by jeikabu** [comment]
They're "byte string literals" (`b""`) [is apparently always](https://doc.rust-lang.org/reference/tokens.html#byte-string-literals) (?)  `&'static [u8; n]`.

**Comment by neachdainn** [comment]
It will make writing code that is compatible on all platforms slightly trickier but as long as it is consistent everywhere I am fine with this.

I.e., 
```rust
// Not compatible on platforms where c_char = i8
nng_setopt_bool(socket, &SOME_OPTION as *const _, false);
// Compatible everywhere
nng_setopt_bool(socket, &SOME_OPTION as *const _ as _, false);
```
